# salizzar/centos-7-ruby
# VERSION	0.0.1

FROM		centos:centos7
MAINTAINER	Marcelo Pinheiro <salizzar@gmail.com>

ENV		HOME		/root

RUN		yum install -y		\
		gcc			\
		gcc-c++			\
		make			\
		ruby-devel		\
		rubygem-bundler		\
		patch			\
		tar

WORKDIR		/root
